### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by hounsellal** [logan-markewich/llama_index_starter_pack#10]
For the life of me I can't figure out how to get the OpenAI API key working in react example. Whenever I upload a file it says:

INFO:openai:error_code=invalid_api_key error_message='Incorrect API key provided: your key*here. You can find your API key at https://platform.openai.com/account/api-keys.' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False

I have supplied my api key as an environment variable. I can't even find the text "your key*here" anywhere in this repository so I have no idea where it's coming from. 

Any ideas?

**Comment by logan-markewich** [comment]
🤔 So you removed this line? https://github.com/logan-markewich/llama_index_starter_pack/blob/main/flask_react/index_server.py#L5

**Comment by logan-markewich** [comment]
I just tried removing that line, and it works for me if the key is in my env

```
export OPENAI_API_KEY=...
python ./index_server.py
```

Then I opened the flask_server.py in another terminal, and one more terminal to run the frontend. Queries + uploading worked fine 🤔 

It might have to do with how you are launching the app? Or it might be a windows thing if you are using powershell/cmd ?

**Comment by hounsellal** [comment]
I've tried putting the api key directly in the code. I've used dotenv. I've done export OPENAI_API_KEY=... and then run the index_server script. Nothing works. I even print out the key in the console before importing llama_index:

openai_api_key = os.getenv('OPENAI_API_KEY')
print(openai_api_key)

... and it shows up correctly. But for some reason I keep getting the same error:

INFO:openai:error_code=invalid_api_key error_message='Incorrect API key provided: your key*here. You can find your API key at https://platform.openai.com/account/api-keys.' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False

**Comment by logan-markewich** [comment]
@hounsellal wow that's kind of crazy!

I would try deleting the repo and re-cloning it maybe? And just hardcode the key into the index_server.py script for now (like it does to start with)?

I think I'm just as lost as you are though haha

Another sanity check is running a quick test script:

```python
import os
os.environ['OPENAI_API_KEY'] = "your key here"

from llama_index import GPTSimpleVectorIndex, Document

index = GPTSimpleVectorIndex.from_documents([Document("My test document")])
```

**Comment by hounsellal** [comment]
Yes, starting from scratch did the trick (putting API key directly into code). I also used poetry to manage my venv this time.

**Comment by logan-markewich** [comment]
Nice! The classic "turn it off and on" again solution 😆 Closing the issue for now then! 👍🏻
