### ISSUE TITLE
Am I the only one who is experiencing problem about Permission to index.json file?

### ISSUE THREAD

**Issue by dglee-rbrain** [logan-markewich/llama_index_starter_pack#16]
I executed streamlit_vector with .cmd and here is my error message.

"PermissionError: [Errno 13] Permission denied: './index.json'"

I tried everything with the permission setting of index.json file and it's not working.

Can anyone help me please?

**Comment by logan-markewich** [comment]
@dglee-rbrain you can try using chmod -R 775 to change the permissions of entire folders.

Not sure why you are hitting that issue though. It might also depend where you are running g the code on your computer, and your operating system

**Comment by dglee-rbrain** [comment]
> @dglee-rbrain you can try using chmod -R 775 to change the permissions of entire folders.
> 
> Not sure why you are hitting that issue though. It might also depend where you are running g the code on your computer, and your operating system 

Thank you. It worked when I changed working directory closer to .py file

**Comment by logan-markewich** [comment]
Perfect!
