### ISSUE TITLE
question in flask_react

### ISSUE THREAD

**Issue by kaiqiangh** [logan-markewich/llama_index_starter_pack#19]
In the folder of flask_react, the file "index_server.py" uses "GPTSimpleVectorIndex" to build indexes . why do not use "GPTVectorStoreIndex" instead? what are different between them?

and is it possible to update the repo with the latest version of llama (0.6.14)? Thanks.

Kind regards.
Kai

**Comment by logan-markewich** [comment]
Yes! All the examples should be using a more recent version of llama index now
