### ISSUE TITLE
I can't run Flask backend.

### ISSUE THREAD

**Issue by assassin990123** [logan-markewich/llama_index_starter_pack#23]
!!! Help me !!!

I ran the commands in the readme to install all dependencies.
```Local Setup
conda create --name llama_index python=3.11
pip install -r requirements.txt
```

But I can't run the index_server.py and that occurs these errors.
![image](https://github.com/logan-markewich/llama_index_starter_pack/assets/130412496/3c964d79-b620-4064-a644-a613ab1f1f29)
![image](https://github.com/logan-markewich/llama_index_starter_pack/assets/130412496/c0eca669-eef8-40cc-a2a6-92881c705e4c)
If you have experience with this, Help me Please!!!

**Comment by logan-markewich** [comment]
Looks like tiktoken is having trouble downloading files

```
import tiktoken
tiktoken.get_encoding("gpt-2")

```

Does the reproduce the error? Not sure how to fix that, something to do with your network/ISP maybe?

**Comment by assassin990123** [comment]
![image](https://github.com/logan-markewich/llama_index_starter_pack/assets/130412496/1e73da3a-b6b9-4393-9b23-a5a03fc85ca8)
Is this right?

**Comment by logan-markewich** [comment]
Looks right to me!

**Comment by assassin990123** [comment]
![image](https://github.com/logan-markewich/llama_index_starter_pack/assets/130412496/94183e8c-5242-4178-8b5f-08996b89fb93)

**Comment by logan-markewich** [comment]
Lol whoops, "gpt2" not "gpt-2"

**Comment by assassin990123** [comment]
But there are ...
![image](https://github.com/logan-markewich/llama_index_starter_pack/assets/130412496/b78cb0f6-d0b6-403a-ae0f-78d9ed610e18)
![image](https://github.com/logan-markewich/llama_index_starter_pack/assets/130412496/02e7ad15-6fa2-44b9-8005-cd29b44a9885)
![image](https://github.com/logan-markewich/llama_index_starter_pack/assets/130412496/0facc2ca-2a5c-4ae4-bfa8-f6a508b9ab14)

**Comment by assassin990123** [comment]
I have to run this backend.
But it is not working.
I tried this over 10 times.
Help me everybody!!1

**Comment by logan-markewich** [comment]
Yea like I said, seems like your network doesn't have access to that url. Not sure what to tell ya 😅

**Comment by logan-markewich** [comment]
Gotta do some network config or something. Pretty outside of my field of knowledge

**Comment by assassin990123** [comment]
If you don't mind, can you share a video recorded how you run this backend server?

**Comment by logan-markewich** [comment]
You arent doing anything wrong, just the computer you are running on is having trouble downloading that file.

You could try running with python3.8 instead, which will use huggingface instead of tiktoken, but you might get a similar error if your network access is restrictive

**Comment by assassin990123** [comment]
> If you don't mind, can you share a video recorded how you run this backend server?

what do you think about this?
I will try again with same version that you run.

**Comment by assassin990123** [comment]
**Help me!!!**

**Comment by assassin990123** [comment]
I change the pc and try again.

![image](https://github.com/logan-markewich/llama_index_starter_pack/assets/130412496/55386e5b-40af-4b5d-a07d-a4fc9547ec88)

Now there is these errors.
How can i fix ?
