### ISSUE TITLE
OSError: [WinError 10049] The requested address is not valid in its context.

### ISSUE THREAD

**Issue by Lufffya** [logan-markewich/llama_index_starter_pack#4]
[https://github.com/logan-markewich/llama_index_starter_pack](url)

run python ./flask_demo.py & and get error:
`OSError: [WinError 10049] The requested address is not valid in its context.`

**Comment by Luffffffy** [comment]
In fact, I did not modify any ports and also checked that were no occupied ports and I have tried using other ports.
However, this error occurred an I have given up using the example.
Thank you!!!

**Comment by logan-markewich** [comment]
@Lufffya sorry to hear about that!

Something running on windows is causing the ports to not be available. You can modify them as I mentioned and then the code should work.

**Comment by Lufffya** [comment]
@logan-markewich Thank you, I ran it successfully!
The problem is that I missed a place:
`BaseManager(('', 5602), b'password')` modify to ` BaseManager(('127.0.0.1', 5602), b'password')`
I don't know anything about "BaseManager", I'm so stupid.

**Comment by logan-markewich** [comment]
@Lufffya Nah not stupid, it's very new to me too! First project where I used it haha

Glad it worked out though 💪
