### ISSUE TITLE
There seems to be a cache during the Q&A process.

### ISSUE THREAD

**Issue by Lufffya** [logan-markewich/llama_index_starter_pack#7]
![image](https://user-images.githubusercontent.com/49063302/228471964-83325281-818d-421f-a59f-26f5abbf10fa.png)

As shown in the picture, I uploaded a wiki on machine learning and asked a question. However, the reply I received was from my previously uploaded review.txt file, even though I had already deleted it and restarted the project.

**Comment by Lufffya** [comment]
![image](https://user-images.githubusercontent.com/49063302/228475670-adbf90b5-60c5-4b90-91ca-491dde6245b1.png)

Then no matter what I ask next, the answer is always the same.

**Comment by logan-markewich** [comment]
@Lufffya ohhh interesting!

There are two cache files here: 
`index_name = "./index.json"`
`pkl_name = "stored_documents.pkl"`

Delete those two files and see if it works?

**Comment by Lufffya** [comment]
I deleted those two files and asked some questions.
It seems that the problem still exists.

![image](https://user-images.githubusercontent.com/49063302/228714338-9897b8cc-97e2-4a88-95d9-e33a4ed5efbb.png)

![image](https://user-images.githubusercontent.com/49063302/228714273-731f7ae0-3325-48f8-8a47-d8f172a24ed6.png)

![image](https://user-images.githubusercontent.com/49063302/228714605-7b0262ea-0236-4d37-b2ec-fb96d512e83a.png)

**Comment by logan-markewich** [comment]
@Lufffya dang, super weird. I'll have to debug this tomorrow. I'll let you know when I find the issue. Thanks for testing though!

**Comment by logan-markewich** [comment]
Hey @Lufffya I figured it out!

I should have noticed this sooner, but try cloning the latest version of the repo

There was a recent PR (https://github.com/logan-markewich/llama_index_starter_pack/commit/b1e1f7c54f97c021f5a85248d467f3323f661d1a) that solves the issue you are having

**Comment by Lufffya** [comment]
@logan-markewich It worked, thank you very much!!!

**Comment by logan-markewich** [comment]
Amazing! 🚀
